TDR-2362 rename ordinal column to UIOrdinal
nationalarchives/tdr-consignment-api-data pull request #205
Opened 2022-09-16 08:44 UTC by juliuswelby

2022-09-20 08:44 UTC, TomJKing reviewed
This is a breaking change. So shouldn't be merged until the application code changes are ready to be merged as well, to minimise the amount of time where the closure metadata form page will be broken.

See task for application code changes: https://national-archives.atlassian.net/browse/TDR-2377

2022-09-20 12:01 UTC, thanhz requested changes
Looks good, just a minor comment. I'm currently working on the changes to the frontend & api to accommodate these changes.

2022-09-20 13:40 UTC, juliuswelby commented
I believe this merge should resolve the failing tests on https://github.com/nationalarchives/tdr-consignment-api/pull/422

2022-09-21 08:30 UTC, thanhz approved these changes

2022-09-21 08:55 UTC, merged